export const ADD_USERINFO = 'ADD_USERINFO'
export const CLEAR_USERINFO = 'CLEAR_USERINFO'

export const ADD_GEOLOCATION = 'ADD_GEOLOCATION'
export const EDIT_GEOLOCATION = 'EDIT_GEOLOCATION'
export const REMOVE_GEOLOCATION = 'REMOVE_GEOLOCATION'
export const CLEAR_GEOLOCATION = 'CLEAR_GEOLOCATION'

export const ADD_FOLDER = 'ADD_FOLDER'
export const EDIT_FOLDER = 'EDIT_FOLDER'
export const REMOVE_FOLDER = 'REMOVE_FOLDER'
export const CLEAR_FOLDER = 'CLEAR_FOLDER'

export const ADD_NOTESUBJECTION = 'ADD_NOTESUBJECTION'
export const REMOVE_NOTESUBJECTION = 'REMOVE_NOTESUBJECTION'
export const CLEAR_NOTESUBJECTION = 'CLEAR_NOTESUBJECTION'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const EDIT_NOTIFICATION = 'EDIT_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
